### ISSUE TITLE
1.0.6 is now broken with BeatSaber 1.6.0 (360 & 90° songs)

### ISSUE THREAD

**Issue by bigrck64** [Ibodan/RumbleEnhancerOculus#2]
Hello !

I love this beatsaber plugin and I'm using it since 8 months without any problem.
He was working correctly with beatsaber 1.0, 1.1, 1.3 and 1.5 !

Unfortunatly, the 1.6 upgrade (with 360 & 90° levels) have break it :-(
Could your rebuild this awesome plugin for this new version of beatsaber ?

Thanks a lot :)

**Comment by Ibodan** [comment]
the latest release would fix this issue
